version: '2'
services:
  app:
    build: .
    env_file:
      - .env
  lb:
    image: dockercloud/haproxy
    links:
      - app
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock